spring:
  datasource:
    password: 1234
    username: security
    url: jdbc:postgresql://localhost:5436/
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

